//! Example use of the `fsm` crate: a door lock opened by a four-digit code.
//!
//! Four states (Locked/Unlocked/Alarm/Maintenance) and seven edges.
//!
//! # Where a variable belongs
//!
//! | Value | Owner | Why |
//! |---|---|---|
//! | [`Unlocked::code_used`] | state node | Meaningless outside the state, written only on entry |
//! | `Env::attempts` | `Env` | Scoped to `Locked` in spirit, but updated by an action |
//!
//! A state node can only be written from `on_enter`/`on_exit`, and those do not
//! run for [`Goto::Internal`] transitions. `attempts` is incremented by
//! `Action::IncrementAttempts` on an internal transition, so it lives in `Env` and
//! is cleared by `Action::ResetAttempts` on entry to `Locked`.

use std::any::Any;

use fsm::{Cond, Domain, Edge, Goto, Ignore, Machine, OnUnknown, Source, StateNode, render};

fsm::tags! {
    enum Tag {
        Locked,
        Unlocked,
        Alarm,
        Maintenance,
    }
}

// Event, Kind, HasKind and the coverage value list all come from this one
// declaration.
fsm::events! {
    #[derive(Clone, Debug)]
    enum Event => Kind {
        EnterCode(u32),
        Timeout,
        Reset,
        MaintenanceToggle,
    }
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
enum Action {
    Unlock,
    Lock,
    Beep,
    IncrementAttempts,
    ResetAttempts,
    SoundAlarm,
    MaintenanceOn,
    MaintenanceOff,
}

/// The outside world.
struct Env {
    correct_code: u32,
    attempts: u32,
    max_attempts: u32,
}

struct Door;

impl Domain for Door {
    type Tag = Tag;
    type Event = Event;
    type EventKind = Kind;
    type Action = Action;
    type Env = Env;

    /// `state` is the state node *after* the transition, so an action may only
    /// read a state-scoped variable on transitions that stay in or enter the state
    /// that owns it.
    fn perform(action: Action, _ev: &Event, state: &dyn StateNode<Self>, world: &mut Env) {
        match action {
            Action::Unlock => match state.as_any().downcast_ref::<Unlocked>() {
                Some(u) => println!("  [action] unlock (code {})", u.code_used),
                None => println!("  [action] unlock"),
            },
            Action::Lock => println!("  [action] lock"),
            Action::Beep => println!("  [action] beep (wrong code)"),
            Action::IncrementAttempts => {
                world.attempts += 1;
                println!("  [action] attempts = {}", world.attempts);
            }
            Action::ResetAttempts => {
                world.attempts = 0;
                println!("  [action] attempts reset");
            }
            Action::SoundAlarm => println!("  [action] alarm on"),
            Action::MaintenanceOn => println!("  [action] maintenance mode on"),
            Action::MaintenanceOff => println!("  [action] maintenance mode off"),
        }
    }

    // all_tags and all_kinds use their defaults, which read the Enumerable impls
    // generated by tags!/events!.
}

fsm::cond_node!(Door, CodeCorrect, |cx| match cx.event {
    Event::EnterCode(code) => Cond::from(*code == cx.world.correct_code),
    _ => Cond::False,
});

fsm::cond_node!(Door, AttemptsExceeded, |cx| Cond::from(
    cx.world.attempts >= cx.world.max_attempts
));

/// A state that captures the event payload it was entered with.
///
/// `on_enter` takes `&mut self`, so a plain `u32` suffices. No other state can
/// reach this variable: [`fsm::Cx`] exposes only the current state's node.
#[derive(Default)]
pub struct Unlocked {
    code_used: u32,
}

impl StateNode<Door> for Unlocked {
    fn tag(&self) -> Tag {
        Tag::Unlocked
    }

    fn on_enter(&mut self, ev: &Event, _world: &Env, out: &mut Vec<Action>) {
        if let Event::EnterCode(code) = ev {
            self.code_used = *code;
        }
        out.push(Action::Unlock);
    }

    /// Clears the state-scoped variable. State nodes are not dropped on
    /// transition, so without this the previous visit's value would leak into the
    /// next one.
    fn on_exit(&mut self, _world: &Env, _out: &mut Vec<Action>) {
        self.code_used = 0;
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}

// States without variables need only the macro.
fsm::state!(Door, Locked, tag: Tag::Locked,
            on_enter: [Action::Lock, Action::ResetAttempts]);
fsm::state!(Door, Alarm, tag: Tag::Alarm, on_enter: [Action::SoundAlarm]);
fsm::state!(Door, Maintenance, tag: Tag::Maintenance,
            on_enter: [Action::MaintenanceOn], on_exit: [Action::MaintenanceOff]);

static EDGES: &[Edge<Door>] = &[
    Edge {
        id: "UNLOCK",
        from: Source::These(&[Tag::Locked]),
        when: Kind::EnterCode,
        check: fsm::check!(CodeCorrect),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Unlocked),
    },
    Edge {
        id: "WRONG_CODE",
        from: Source::These(&[Tag::Locked]),
        when: Kind::EnterCode,
        check: fsm::check!(!CodeCorrect && !AttemptsExceeded),
        unknown: OnUnknown::Deny,
        run: &[Action::Beep, Action::IncrementAttempts],
        goto: Goto::Internal,
    },
    Edge {
        id: "TRIGGER_ALARM",
        from: Source::These(&[Tag::Locked]),
        when: Kind::EnterCode,
        check: fsm::check!(!CodeCorrect && AttemptsExceeded),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Alarm),
    },
    Edge {
        id: "RELOCK",
        from: Source::These(&[Tag::Unlocked]),
        when: Kind::Timeout,
        check: fsm::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Locked),
    },
    Edge {
        id: "ALARM_RESET",
        from: Source::These(&[Tag::Alarm]),
        when: Kind::Reset,
        check: fsm::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Locked),
    },
    Edge {
        id: "ENTER_MAINTENANCE",
        from: Source::These(&[Tag::Locked]),
        when: Kind::MaintenanceToggle,
        check: fsm::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Maintenance),
    },
    Edge {
        id: "EXIT_MAINTENANCE",
        from: Source::These(&[Tag::Maintenance]),
        when: Kind::MaintenanceToggle,
        check: fsm::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Locked),
    },
];

static IGNORES: &[Ignore<Door>] = &[
    Ignore {
        from: Source::These(&[Tag::Locked, Tag::Alarm, Tag::Maintenance]),
        when: &[Kind::Timeout],
        why: "the timeout only drives the automatic relock from Unlocked",
    },
    Ignore {
        from: Source::AnyExcept(&[Tag::Alarm]),
        when: &[Kind::Reset],
        why: "Reset clears the alarm, so it is only meaningful in Alarm",
    },
    Ignore {
        from: Source::These(&[Tag::Unlocked, Tag::Alarm, Tag::Maintenance]),
        when: &[Kind::EnterCode],
        why: "a code is entered to unlock, so it is only accepted in Locked",
    },
    Ignore {
        from: Source::These(&[Tag::Unlocked, Tag::Alarm]),
        when: &[Kind::MaintenanceToggle],
        why: "maintenance is toggled only between Locked and Maintenance",
    },
];

fn main() {
    let mut world = Env {
        correct_code: 1234,
        attempts: 0,
        max_attempts: 2,
    };
    let mut m = Machine::new(
        Tag::Locked,
        vec![
            Box::new(Locked),
            Box::new(Unlocked::default()),
            Box::new(Alarm),
            Box::new(Maintenance),
        ],
        EDGES,
        IGNORES,
    );

    let steps: &[(&str, Event)] = &[
        ("wrong code, 1st", Event::EnterCode(9999)),
        ("wrong code, 2nd", Event::EnterCode(8888)),
        ("wrong code, 3rd -> alarm", Event::EnterCode(7777)),
        ("operator reset", Event::Reset),
        ("correct code", Event::EnterCode(1234)),
        ("timeout -> relock", Event::Timeout),
        ("enter maintenance", Event::MaintenanceToggle),
        ("leave maintenance", Event::MaintenanceToggle),
        // ResetAttempts ran on entry to Locked, so this counts from 1 again.
        ("wrong code (counter was cleared)", Event::EnterCode(6666)),
    ];

    println!("state = {:?}", m.tag());
    for (desc, ev) in steps {
        println!("dispatch: {desc} ({ev:?})");
        if let Some(taken) = m.dispatch(ev, &mut world) {
            println!("  edge = {}, state = {:?}", taken.edge, m.tag());
        } else {
            println!("  (ignored)");
        }
    }

    let diagram = render::to_mermaid::<Door>(Tag::Locked, EDGES);
    let md = format!("# Door lock FSM\n\n```mermaid\n{diagram}```\n");
    std::fs::create_dir_all("example").expect("failed to create example dir");
    std::fs::write("example/door_lock.md", &md).expect("failed to write example/door_lock.md");
    println!("\nmermaid diagram written to example/door_lock.md");

    let coverage = render::coverage::<Door>(Tag::Locked, EDGES, IGNORES);
    println!("coverage clean: {}", coverage.is_clean());
}
